import {ReliableStudio,isMixerOnlyChange as originalLiveChange} from './reliable-audio.js';
import {copy,validateProject,endTime} from './model.js';
import {dbGain,measure} from './core.js';
import {memoryLimit} from './files.js';
import {hasMixer,audibleMixIds,mixTailSeconds,mixerChangeIsLive} from './mixer-schema.js';
import {hasProducer,producerChangeIsLive} from './producer-schema.js';
import {masterProducer,masteringMetrics} from './producer-dsp.js';
import {MixerGraph,prepareDynamics} from './mixer-graph.js';
export function isMixerOnlyChange(a,b){if(hasProducer(a)||hasProducer(b))return hasProducer(a)&&hasProducer(b)&&mixerChangeIsLive(a,b)&&producerChangeIsLive(a,b);return hasMixer(a)||hasMixer(b)?mixerChangeIsLive(a,b):originalLiveChange(a,b);}
export class MixerStudio extends ReliableStudio {
  constructor(status){super(status);this.mixContexts=new WeakMap();this.graph=null;}
  async prepare(project,trackId,raw=false){if(!hasMixer(project)||raw)return super.prepare(project,trackId,raw);const adjusted=copy(project),audible=audibleMixIds(project);for(const t of adjusted.tracks){t.mute=!audible.has(t.id);t.solo=false;}return super.prepare(adjusted,trackId,raw);}
  async play(project,options={}){const generation=this.transportGeneration;if(hasMixer(project)){const ctx=await this.init();await prepareDynamics(ctx);if(generation!==this.transportGeneration)throw Error('Mixer playback preparation canceled.');}const origin=await super.play(project,options);this.baseMixLength=this.length;if(hasMixer(project)&&!project.loop)this.length+=mixTailSeconds(project);this.graph?.scheduleAutomation(project,origin,this.position,this.length);return origin;}
  liveBus(track,destination){if(!hasMixer(this.playbackProject))return super.liveBus(track,destination);if(!this.graph)this.graph=new MixerGraph(this.ctx,this.playbackProject,destination);return this.graph.input(track.id);}
  async prepareMixRender(context,project,{raw=false,start=0,duration=null}={}){if(raw||!hasMixer(project))return null;await prepareDynamics(context);const graph=new MixerGraph(context,project,context.destination);this.mixContexts.set(context,graph);graph.scheduleAutomation(project,0,start,duration??context.length/context.sampleRate);return graph;}
  finishMixRender(context){this.mixContexts.get(context)?.dispose();this.mixContexts.delete(context);}
  mixTailSeconds(project,raw=false){return mixTailSeconds(project,raw);}
  schedule(ctx,item,origin,position,duration,destination){const graph=this.mixContexts.get(ctx);const live=ctx===this.ctx&&hasMixer(this.playbackProject);if(!graph&&!live)return super.schedule(ctx,item,origin,position,duration,destination);const {c,t,a}=item,offset=Math.max(0,position-c.start),delay=Math.max(0,c.start-position),full=a.channels[0].length/a.rate;if(offset>=full||delay>=duration)return;const source=ctx.createBufferSource(),gain=ctx.createGain();source.buffer=this.buffer(ctx,a.channels,a.rate);gain.gain.value=dbGain(c.gainDb);source.connect(gain).connect(live?this.liveBus(t,destination):graph.input(t.id));if(live)this.nodes.push(source);source.onended=()=>{source.disconnect();gain.disconnect();if(live)this.nodes=this.nodes.filter(v=>v!==source);};source.start(origin+delay,offset,Math.min(full-offset,duration-delay));}
  updateMixer(project){if(!hasMixer(this.playbackProject))return super.updateMixer(project);if(!this.playing)return;if(!mixerChangeIsLive(this.playbackProject,project)||(hasProducer(this.playbackProject)||hasProducer(project))&&!producerChangeIsLive(this.playbackProject,project))throw Error('Stop playback before changing routing, sidechain routing, automation points or ambience timing.');this.graph?.update(project);if(!this.loop)this.length=Math.max(this.length,this.baseMixLength+mixTailSeconds(project));const cursor=this.cursor();this.graph?.scheduleAutomation(project,this.ctx.currentTime+.01,cursor,Math.max(0,this.position+this.length-cursor));this.playbackProject=copy(project);}
  stopPlayback(){super.stopPlayback();this.graph?.dispose();this.graph=null;}
  async render(project,{master=false,trackId=null,raw=false}={}){if(!hasMixer(project)||raw)return super.render(project,{master,trackId,raw});validateProject(project,this.assets);if(!project.clips.length)throw Error('Import or record audio first.');const snapshot=copy(project),prepared=await this.prepare(snapshot,trackId,raw),rate=44100;const duration=prepared.reduce((e,v)=>Math.max(e,v.c.start+v.a.channels[0].length/v.a.rate),endTime(snapshot)+1.5)+mixTailSeconds(snapshot);if(duration*rate*8>memoryLimit()/2)throw Error('Mixer render exceeds the device memory budget.');const context=new OfflineAudioContext(2,Math.ceil(duration*rate),rate);let channels;try{await this.prepareMixRender(context,snapshot,{start:0,duration});for(const v of prepared)this.schedule(context,v,0,0,duration,context.destination);const b=await context.startRendering();channels=[b.getChannelData(0).slice(),b.getChannelData(1).slice()];}finally{this.finishMixRender(context);}let producerMaster=null;if(master&&hasProducer(snapshot)&&snapshot.producer.mastering.enabled){producerMaster=masterProducer(channels,rate,snapshot.producer.mastering);channels=producerMaster.channels;}else if(master){const result=await this.process('master',{channels,rate,project:snapshot},channels.map(v=>v.buffer));channels=result.channels;}return {channels,rate,metrics:measure(channels),producerMetrics:hasProducer(snapshot)?masteringMetrics(channels,rate):null,producerMaster};}
}
