import {hasMixer,strip,newRack,audibleMixIds,delaySeconds,validateMixer} from './mixer-schema.js';
import {hasProducer,automationValue,targetRange} from './producer-schema.js';
const registered=new WeakMap();
export function prepareDynamics(ctx){if(!registered.has(ctx)){const p=ctx.audioWorklet.addModule(new URL('./mix-worklet.js',import.meta.url)).catch(e=>{registered.delete(ctx);throw Error('The mixer audio processor could not load. Nothing was rendered without it: '+e.message);});registered.set(ctx,p);}return registered.get(ctx);}
const amp=db=>10**(db/20);
const set=(parameter,value,ctx,smooth)=>{if(!smooth){parameter.value=value;return;}const now=ctx.currentTime;if(parameter.cancelAndHoldAtTime)parameter.cancelAndHoldAtTime(now);else{parameter.cancelScheduledValues(now);parameter.setValueAtTime(parameter.value,now);}parameter.setTargetAtTime(value,now,0.008);};
export function impulseChannels(rate,{seconds,predelayMs,dampingHz,width,seed}){
  const delay=Math.round(predelayMs*rate/1000),n=Math.ceil(seconds*rate),channels=[new Float32Array(n+delay),new Float32Array(n+delay)];let state=seed>>>0;
  const rand=()=>{state=(Math.imul(state,1664525)+1013904223)>>>0;return state/2147483648-1;};
  const cutoff=Math.min(dampingHz,rate*0.45),alpha=1-Math.exp(-2*Math.PI*cutoff/rate);let l=0,r=0;const energy=[0,0];
  for(let i=0;i<n;i++){const a=rand(),b=rand();l+=alpha*(a-l);r+=alpha*((a*(1-width)+b*width)-r);const env=Math.exp(-6.91*i/n)*Math.min(1,i/Math.max(1,rate*0.004),(n-1-i)/Math.max(1,rate*0.005));channels[0][i+delay]=l*env;channels[1][i+delay]=r*env;energy[0]+=(l*env)**2;energy[1]+=(r*env)**2;}
  for(let ch=0;ch<2;ch++){const scale=0.6/Math.sqrt(Math.max(energy[ch],1e-20));for(let i=delay;i<channels[ch].length;i++)channels[ch][i]*=scale;}
  return channels;
}
export class MixerGraph {
  constructor(ctx,project,destination){validateMixer(project);if(!hasMixer(project))throw Error('Enable the mixer before creating its graph.');this.ctx=ctx;this.nodes=[];this.worklets=[];this.strips=new Map();this.buses=new Map();this.meters=new Map();this.disposed=false;this.sidechainLink=null;
    this.sum=this.gain();this.master=this.gain();this.sum.connect(this.master);this.master.connect(this.meter('main',this.master)).connect(destination);
    const m=project.mixer;
    this.delayIn=this.gain();this.delayHP=this.filter('highpass',180);this.delayLP=this.filter('lowpass',6000);this.delayReturn=this.gain();this.delayIn.connect(this.delayHP).connect(this.delayLP);const time=delaySeconds(project);
    for(let i=1;i<=m.delay.repeats;i++){const d=this.node(ctx.createDelay(time*i+0.01));d.delayTime.value=time*i;const level=this.gain(m.delay.feedback**(i-1));this.delayLP.connect(d).connect(level).connect(this.delayReturn);}this.delayReturn.connect(this.meter('delay',this.delayReturn)).connect(this.sum);
    this.reverbIn=this.gain();const convolver=this.node(ctx.createConvolver());convolver.normalize=false;const channels=impulseChannels(ctx.sampleRate,m.reverb);const response=ctx.createBuffer(2,channels[0].length,ctx.sampleRate);channels.forEach((v,i)=>response.copyToChannel(v,i));convolver.buffer=response;this.reverbReturn=this.gain();this.reverbIn.connect(convolver).connect(this.reverbReturn);this.reverbReturn.connect(this.meter('reverb',this.reverbReturn)).connect(this.sum);
    for(const b of m.buses){const input=this.gain(),rack=this.rack(input),level=this.gain();rack.output.connect(level);const grim=this.worklet('iv-grim-v1',1),sidechain=this.worklet('iv-sidechain-v1',2),grimDelaySend=this.gain(0),grimReverbSend=this.gain(0);level.connect(grim).connect(sidechain).connect(this.meter(b.id,sidechain)).connect(this.sum);grim.connect(grimDelaySend).connect(this.delayIn);grim.connect(grimReverbSend).connect(this.reverbIn);const state={input,rack,level,grim,sidechain,grimDelaySend,grimReverbSend,sidechainReduction:0};sidechain.port.onmessage=e=>{state.sidechainReduction=e.data.reduction||0;};this.buses.set(b.id,state);}
    for(const t of project.tracks){const input=this.gain(),rack=this.rack(input),level=this.gain(),delaySend=this.gain(),reverbSend=this.gain();rack.output.connect(level);const spec=strip(t),tap=spec.sendTap==='pre'?rack.output:level;tap.connect(delaySend).connect(this.delayIn);tap.connect(reverbSend).connect(this.reverbIn);level.connect(this.meter(t.id,level)).connect(this.buses.get(spec.route)?.input||this.sum);this.strips.set(t.id,{input,rack,level,delaySend,reverbSend});}
    this.connectSidechain(project);this.update(project,false);
  }
  node(n){this.nodes.push(n);return n;}
  gain(value=1){const n=this.node(this.ctx.createGain());n.gain.value=value;return n;}
  filter(type,hz){const n=this.node(this.ctx.createBiquadFilter());n.type=type;n.frequency.value=Math.min(hz,this.ctx.sampleRate*0.45);n.Q.value=0.7071;return n;}
  worklet(name,inputs=1){const n=this.node(new AudioWorkletNode(this.ctx,name,{numberOfInputs:inputs,numberOfOutputs:1,outputChannelCount:[2],channelCount:2,channelCountMode:'explicit'}));this.worklets.push(n);return n;}
  rack(input){const hp=this.filter('highpass',80),dry=this.gain(),filtered=this.gain(0),tone=this.gain();input.connect(dry).connect(tone);input.connect(hp).connect(filtered).connect(tone);const eq=[];let previous=tone;for(const b of newRack().eq.bands){const f=this.filter(b.type,b.hz);f.gain.value=0;previous.connect(f);previous=f;eq.push(f);}const pan=this.node(this.ctx.createStereoPanner());previous.connect(pan);const dynamics=this.worklet('iv-mixer-dynamics-v1',1);pan.connect(dynamics);const rack={hp,dry,filtered,eq,pan,dynamics,output:dynamics,reduction:0};dynamics.port.onmessage=e=>{rack.reduction=e.data.reduction;};return rack;}
  meter(id,source){const output=this.gain(),splitter=this.node(this.ctx.createChannelSplitter(2));output.connect(splitter);const channels=[];for(let ch=0;ch<2;ch++){const node=this.node(this.ctx.createAnalyser());node.fftSize=2048;node.smoothingTimeConstant=0;splitter.connect(node,ch);channels.push({node,data:new Float32Array(2048)});}this.meters.set(id,{channels,heldPeak:0});return output;}
  connectSidechain(project){const sc=project.producer?.sidechain;if(!hasProducer(project)||!sc?.keyBus||!sc?.targetBus||sc.keyBus===sc.targetBus)return;const key=this.buses.get(sc.keyBus),target=this.buses.get(sc.targetBus);if(!key||!target)return;key.level.connect(target.sidechain,0,1);this.sidechainLink={keyBus:sc.keyBus,targetBus:sc.targetBus};}
  updateRack(rack,spec,pan,smooth){const c=this.ctx,active=!spec.bypass;set(rack.pan.pan,pan,c,smooth);set(rack.hp.frequency,Math.min(spec.highpass.hz,c.sampleRate*.45),c,smooth);set(rack.dry.gain,active&&spec.highpass.enabled?0:1,c,smooth);set(rack.filtered.gain,active&&spec.highpass.enabled?1:0,c,smooth);spec.eq.bands.forEach((b,i)=>{const f=rack.eq[i];f.type=b.type;set(f.frequency,Math.min(b.hz,c.sampleRate*.45),c,smooth);set(f.Q,b.q,c,smooth);set(f.gain,active&&spec.eq.enabled?b.db:0,c,smooth);});for(const [key,value] of Object.entries(spec.compressor)){set(rack.dynamics.parameters.get(key),key==='enabled'?(active&&value?1:0):value,c,smooth);}}
  updateProducer(project,smooth){const active=hasProducer(project),producer=project.producer,grim=producer?.grim,sc=producer?.sidechain,c=this.ctx;for(const [id,bus] of this.buses){const grimOn=active&&grim?.enabled&&grim.targetBus===id;for(const key of ['darkness','weight','bite','clarity','glitch'])set(bus.grim.parameters.get(key),grim?.[key]??0,c,smooth);set(bus.grim.parameters.get('bpm'),project.bpm,c,smooth);set(bus.grim.parameters.get('enabled'),grimOn?1:0,c,smooth);set(bus.grimDelaySend.gain,grimOn&&!project.mixer.delayMute?(grim.space*.18):0,c,smooth);set(bus.grimReverbSend.gain,grimOn&&!project.mixer.reverbMute?(grim.space*.35):0,c,smooth);const duckOn=active&&sc?.enabled&&sc.targetBus===id;for(const key of ['threshold','ratio','knee','attackMs','releaseMs','maxReductionDb'])set(bus.sidechain.parameters.get(key),sc?.[key]??0,c,smooth);set(bus.sidechain.parameters.get('enabled'),duckOn?1:0,c,smooth);}}
  update(project,smooth=true){if(this.disposed)return;validateMixer(project);const m=project.mixer,ids=audibleMixIds(project),c=this.ctx;for(const t of project.tracks){const s=strip(t),node=this.strips.get(t.id);if(!node)throw Error('Mixer topology changed; restart playback.');const audible=ids.has(t.id);this.updateRack(node.rack,s.rack,t.pan,smooth);set(node.level.gain,audible?amp(t.gainDb):0,c,smooth);set(node.delaySend.gain,audible?s.delaySend:0,c,smooth);set(node.reverbSend.gain,audible?s.reverbSend:0,c,smooth);}for(const b of m.buses){const node=this.buses.get(b.id);if(!node)throw Error('Bus topology changed; restart playback.');this.updateRack(node.rack,b.rack,0,smooth);set(node.level.gain,b.mute?0:amp(b.gainDb),c,smooth);}set(this.master.gain,amp(m.masterDb),c,smooth);set(this.delayReturn.gain,m.delayMute?0:amp(m.delayReturnDb),c,smooth);set(this.reverbReturn.gain,m.reverbMute?0:amp(m.reverbReturnDb),c,smooth);set(this.delayHP.frequency,Math.min(m.delay.lowcut,c.sampleRate*.45),c,smooth);set(this.delayLP.frequency,Math.min(m.delay.highcut,c.sampleRate*.45),c,smooth);this.updateProducer(project,smooth);}
  automationParam(project,target){const [kind,id,param]=String(target).split(':');if(kind==='track'){const t=project.tracks.find(x=>x.id===id),node=this.strips.get(id);if(!t||!node)return null;if(param==='gainDb')return {param:node.level.gain,transform:amp,fallback:t.gainDb};if(param==='pan')return {param:node.rack.pan.pan,transform:v=>v,fallback:t.pan};const spec=strip(t);if(param==='delaySend')return {param:node.delaySend.gain,transform:v=>v,fallback:spec.delaySend};if(param==='reverbSend')return {param:node.reverbSend.gain,transform:v=>v,fallback:spec.reverbSend};}if(kind==='bus'){const b=project.mixer.buses.find(x=>x.id===id),node=this.buses.get(id);if(b&&node&&param==='gainDb')return {param:node.level.gain,transform:amp,fallback:b.gainDb};}if(target==='master:gainDb')return {param:this.master.gain,transform:amp,fallback:project.mixer.masterDb};return null;}
  scheduleAutomation(project,origin,position,duration){if(!hasProducer(project)||!project.producer.automation?.enabled)return;const loop=!!project.loop,loopStart=project.loopStart,loopEnd=project.loopEnd,loopSpan=Math.max(.01,loopEnd-loopStart);for(const lane of project.producer.automation.lanes){if(!lane.enabled||!lane.points.length||!targetRange(project,lane.target))continue;const item=this.automationParam(project,lane.target);if(!item)continue;const p=item.param;p.cancelScheduledValues(origin);const scheduleRange=(from,to,at,reset)=>{const initial=automationValue(project,lane.target,from,item.fallback);if(reset)p.setValueAtTime(item.transform(initial),at);for(const point of lane.points){if(point.time<=from||point.time>to)continue;const when=at+(point.time-from),value=item.transform(point.value);if(point.curve==='hold')p.setValueAtTime(value,when);else p.linearRampToValueAtTime(value,when);}};if(!loop){scheduleRange(position,position+Math.max(0,duration),origin,true);continue;}const firstEnd=Math.min(loopEnd,position+Math.max(0,duration));scheduleRange(position,firstEnd,origin,true);let at=origin+(firstEnd-position);const totalPoints=Math.max(1,lane.points.filter(x=>x.time>=loopStart&&x.time<=loopEnd).length),repeats=Math.max(8,Math.min(128,Math.floor(4096/totalPoints)));for(let cycle=0;cycle<repeats;cycle++){scheduleRange(loopStart,loopEnd,at,true);at+=loopSpan;}}}
  input(trackId){const node=this.strips.get(trackId);if(!node)throw Error('Missing mixer track.');return node.input;}
  readMeters(){const result={};if(this.disposed)return result;for(const [id,m] of this.meters){let peak=0,energy=0,count=0;for(const channel of m.channels){channel.node.getFloatTimeDomainData(channel.data);for(const v of channel.data){peak=Math.max(peak,Math.abs(v));energy+=v*v;count++;}}m.heldPeak=Math.max(m.heldPeak,peak);const bus=this.buses.get(id);result[id]={peakDb:20*Math.log10(Math.max(peak,1e-8)),rmsDb:10*Math.log10(Math.max(energy/Math.max(1,count),1e-16)),heldPeakDb:20*Math.log10(Math.max(m.heldPeak,1e-8)),reductionDb:(this.strips.get(id)||bus)?.rack.reduction||0,sidechainReductionDb:bus?.sidechainReduction||0};}return result;}
  resetPeaks(){for(const m of this.meters.values())m.heldPeak=0;}
  dispose(){if(this.disposed)return;this.disposed=true;for(const n of this.worklets){n.port.onmessage=null;n.port.postMessage('dispose');n.port.close();}for(const n of this.nodes){try{n.disconnect();}catch{}}this.nodes=[];this.worklets=[];this.meters.clear();this.strips.clear();this.buses.clear();}
}
