import {hasMixer,enableMixer,newStrip,newRack,DIVISIONS,rackPreset} from './mixer-schema.js';
const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
export function installMixerUI({studio,getState,edit,run,requireStopped,dialog,closeDialog,play,stop}){
  const open=el('button','Mixer & effects');open.id='core3Mixer';document.getElementById('sessionSafety').prepend(open);
  let target='',meterRows=new Map();
  function change(fn){return run(()=>{if(getState().collaboration&&getState().collaboration.protocol!=='collab-v2')throw Error('This mixer requires Core 6 collaboration.');edit(fn);});}
  function btn(text,fn,id){const b=el('button',text);if(id)b.id=id;b.onclick=()=>run(fn);return b;}
  function control(label,value,fn,{min,max,step=1,choices,check=false,id,help}={}){
    const wrap=el('label',undefined,'field'),head=el('span',label),input=el(choices?'select':'input');
    input.setAttribute('aria-label',label);if(id)input.id=id;
    if(choices){for(const [val,text] of choices){const opt=el('option',text);opt.value=val;input.append(opt);}input.value=String(value);}
    else if(check){input.type='checkbox';input.checked=value;}
    else{input.type='number';input.min=min;input.max=max;input.step=step;input.value=value;}
    if(help){const tip=el('button','i','info');tip.type='button';tip.setAttribute('aria-label','About '+label);tip.onclick=e=>{e.preventDefault();const details=el('p',help,'fine');details.className='mixHelp fine';const prior=wrap.querySelector('.mixHelp');if(prior)prior.remove();else wrap.append(details);};head.append(tip);}
    input.onchange=()=>change(p=>fn(p,choices?input.value:check?input.checked:Number(input.value)));wrap.append(head,input);return wrap;
  }
  function meter(id,label){const row=el('div',undefined,'mixMeter'),name=el('strong',label),readout=el('output','Stopped · peak/RMS');row.append(name,readout);meterRows.set(id,readout);return row;}
  function rackPanel(rack,modify){const box=el('section',undefined,'mixInserts');box.append(el('h3','Insert rack · after existing vocal processing'),el('p','These are extra inserts. Existing tuning, GRIM character, and legacy effects remain intact. Use Insert bypass to compare; reduce old compression/ambience deliberately rather than stacking it unintentionally.','fine'));
    const presets=el('div',undefined,'mixActions');for(const name of ['Neutral','Clean lead','Controlled double','Parallel punch','GRIM body'])presets.append(btn(name,()=>{edit(p=>Object.assign(modify(p),rackPreset(name)));show();}));box.append(presets);
    box.append(control('Bypass insert rack',rack.bypass,(p,v)=>modify(p).bypass=v,{check:true,id:'mixRackBypass',help:'Bypasses this new high-pass, EQ and compressor only. Fader, pan, routing and shared sends remain active.'}));
    const hp=el('div',undefined,'mixFields');hp.append(control('High-pass enabled',rack.highpass.enabled,(p,v)=>modify(p).highpass.enabled=v,{check:true,id:'mixHPEnabled'}),control('High-pass Hz',rack.highpass.hz,(p,v)=>modify(p).highpass.hz=v,{min:20,max:4000,id:'mixHPHz',help:'12 dB/octave filtering before EQ. Frequencies above this context’s safe Nyquist limit are clamped.'}));box.append(hp);
    box.append(control('EQ enabled',rack.eq.enabled,(p,v)=>modify(p).eq.enabled=v,{check:true,id:'mixEQEnabled'}));
    for(let i=0;i<4;i++){const b=rack.eq.bands[i],row=el('div',undefined,'mixFields');row.append(control('Band '+(i+1)+' type',b.type,(p,v)=>modify(p).eq.bands[i].type=v,{choices:[['lowshelf','Low shelf'],['peaking','Bell'],['highshelf','High shelf']]}),control('Band '+(i+1)+' Hz',b.hz,(p,v)=>modify(p).eq.bands[i].hz=v,{min:20,max:20000,id:'mixBandHz'+i}),control('Band '+(i+1)+' dB',b.db,(p,v)=>modify(p).eq.bands[i].db=v,{min:-18,max:18,step:0.5,id:'mixBandDb'+i}),control('Band '+(i+1)+' Q',b.q,(p,v)=>modify(p).eq.bands[i].q=v,{min:.1,max:12,step:.1,help:'Bell bandwidth: higher is narrower. Q is retained but does not control the shelf slope in this engine.'}));box.append(row);}
    box.append(el('h3','Linked vocal compressor'),el('p','Stereo-linked peak-envelope compression, no look-ahead and no hidden makeup gain. Not a brickwall limiter. Parallel blend has no intentional delay between dry and compressed paths.','fine'));
    const comp=el('div',undefined,'mixFields');comp.append(control('Compressor enabled',rack.compressor.enabled,(p,v)=>modify(p).compressor.enabled=v,{check:true,id:'mixCompEnabled'}));
    for(const [key,label,min,max,step] of [['threshold','Threshold dB',-60,0,1],['ratio','Ratio',1,20,.1],['knee','Knee dB',0,24,1],['attackMs','Attack ms',.1,100,.1],['releaseMs','Release ms',10,1500,10],['makeupDb','Makeup dB',-18,18,.5],['blend','Parallel blend',0,1,.05]])comp.append(control(label,rack.compressor[key],(p,v)=>modify(p).compressor[key]=v,{min,max,step,id:'mixComp-'+key}));box.append(comp);return box;
  }
  function show(){requireStopped();const {project:p,collaboration}=getState();meterRows=new Map();const root=el('div',undefined,'core3-mixer');
    root.append(el('p','Core 3 mixer: tracks → optional vocal bus → main. Shared effects return directly to main. Routing, send tap and ambience-time edits stop playback; levels, EQ and compressor settings stay live.','dialog-note'));
    if(!p.mixer){root.append(el('p','Older projects retain their original path until you enable this mixer. Enabling creates arrangement format v2, which older Core 2 readers refuse rather than ignoring its routing. Export a backup first.','fine'),btn('Enable Core 3 mixer',()=>{if(collaboration&&collaboration.protocol!=='collab-v2')throw Error('This mixer requires Core 6 collaboration.');if(studio.playing)throw Error('Stop playback before enabling the mixer.');if(!confirm('Enable Core 3 routing for this project? Old Core 2 readers cannot open v2. Source recordings and original processing remain intact; keep a backup.'))return;edit(enableMixer);show();},'enableCore3Mixer'));dialog('Mixer & effects · Core 3',root);return;}
    if(collaboration&&collaboration.protocol!=='collab-v2')throw Error('This mixer requires Core 6 collaboration.');
    const top=el('div',undefined,'mixActions');top.append(btn('Play mix',()=>play(),'mixPlay'),btn('Stop mix',()=>stop(),'mixStop'),btn('Reset peak holds',()=>studio.graph?.resetPeaks()),btn(p.mixer.enabled?'Bypass new mixer':'Enable new mixer',()=>{edit(n=>{n.mixer.enabled=!n.mixer.enabled;});show();},'mixBypass'));root.append(top);
    root.append(el('p',p.mixer.enabled?'Mixer active · existing track processing still runs before these inserts.':'Mixer bypassed · controls are retained but only the previous track path is heard.','fine'));
    const options=[...p.tracks.map(t=>[t.id,'Track · '+t.name]),...p.mixer.buses.map(b=>[b.id,'Bus · '+b.name]),['returns','Main & shared effects']];if(!options.some(x=>x[0]===target))target=options[0]?.[0]||'returns';
    const selector=el('label','Channel','field'),select=el('select');select.id='mixTarget';select.setAttribute('aria-label','Mixer channel');for(const [v,name] of options){const o=el('option',name);o.value=v;select.append(o);}select.value=target;select.onchange=()=>{target=select.value;show();};selector.append(select);root.append(selector);
    const t=p.tracks.find(t=>t.id===target),bus=p.mixer.buses.find(b=>b.id===target);
    if(t){const s=t.mixStrip||newStrip(),get=n=>{const item=n.tracks.find(x=>x.id===t.id);item.mixStrip??=newStrip();return item.mixStrip;};const fields=el('div',undefined,'mixFields');
      fields.append(control('Output bus',s.route,(n,v)=>get(n).route=v,{choices:[['main','Main'],...p.mixer.buses.map(b=>[b.id,b.name])],id:'mixRoute',help:'Tracks can feed one bus or main. Buses feed main only; feedback routes cannot be created.'}),control('Track level dB',t.gainDb,(n,v)=>n.tracks.find(x=>x.id===t.id).gainDb=v,{min:-60,max:12,step:.5,id:'mixTrackGain'}),control('Track pan',t.pan,(n,v)=>n.tracks.find(x=>x.id===t.id).pan=v,{min:-1,max:1,step:.05}),control('Mute track',t.mute,(n,v)=>n.tracks.find(x=>x.id===t.id).mute=v,{check:true,id:'mixTrackMute'}),control('Solo track',t.solo,(n,v)=>n.tracks.find(x=>x.id===t.id).solo=v,{check:true}),control('Send tap',s.sendTap,(n,v)=>get(n).sendTap=v,{choices:[['post','Post fader'],['pre','Pre fader']],id:'mixSendTap',help:'Pre-fader ignores the track level but still follows mute/solo and bus mute. Existing effect tails ring out until the return is muted.'}),control('Delay send',s.delaySend,(n,v)=>get(n).delaySend=v,{min:0,max:1,step:.02,id:'mixDelaySend'}),control('Reverb send',s.reverbSend,(n,v)=>get(n).reverbSend=v,{min:0,max:1,step:.02,id:'mixReverbSend'}));root.append(fields,meter(t.id,t.name),rackPanel(s.rack,n=>get(n).rack));
    }else if(bus){const get=n=>n.mixer.buses.find(b=>b.id===bus.id);const fields=el('div',undefined,'mixFields');fields.append(control('Bus level dB',bus.gainDb,(n,v)=>get(n).gainDb=v,{min:-60,max:12,step:.5,id:'mixBusGain'}),control('Mute bus',bus.mute,(n,v)=>get(n).mute=v,{check:true,id:'mixBusMute'}),control('Solo bus',bus.solo,(n,v)=>get(n).solo=v,{check:true,id:'mixBusSolo'}));root.append(fields,meter(bus.id,bus.name),rackPanel(bus.rack,n=>get(n).rack));
    }else{const m=p.mixer,fields=el('div',undefined,'mixFields');fields.append(control('Main trim dB',m.masterDb,(n,v)=>n.mixer.masterDb=v,{min:-24,max:6,step:.5,id:'mixMasterDb'}));root.append(fields,meter('main','Main output'));
      const delay=el('section');delay.append(el('h3','Tempo delay · finite repeat pattern'),el('p','Up to six filtered repeats. Repeat decay controls each following tap; this is not an unbounded feedback delay.','fine'));const d=el('div',undefined,'mixFields');d.append(control('Delay division',m.delay.division,(n,v)=>n.mixer.delay.division=v,{choices:Object.keys(DIVISIONS).map(k=>[k,k]),id:'mixDelayDivision'}),control('Repeat count',m.delay.repeats,(n,v)=>n.mixer.delay.repeats=v,{min:1,max:6,id:'mixRepeats'}),control('Repeat decay',m.delay.feedback,(n,v)=>n.mixer.delay.feedback=v,{min:0,max:.8,step:.05}),control('Delay low cut Hz',m.delay.lowcut,(n,v)=>n.mixer.delay.lowcut=v,{min:20,max:3000}),control('Delay high cut Hz',m.delay.highcut,(n,v)=>n.mixer.delay.highcut=v,{min:1000,max:20000}),control('Delay return dB',m.delayReturnDb,(n,v)=>n.mixer.delayReturnDb=v,{min:-60,max:6,step:.5,id:'mixDelayReturn'}),control('Mute delay return',m.delayMute,(n,v)=>n.mixer.delayMute=v,{check:true,id:'mixDelayMute'}));delay.append(d,meter('delay','Delay return'));root.append(delay);
      const reverb=el('section');reverb.append(el('h3','Seeded stereo convolution ambience'),el('p','A repeatable synthesized impulse, not a measured real room. Tail length, predelay, width and damping change its shape. Full export tails include the declared response plus a short filter-settling allowance.','fine'));const r=el('div',undefined,'mixFields');for(const [key,label,min,max,step] of [['seconds','Reverb length seconds',.2,5,.1],['predelayMs','Predelay ms',0,150,1],['dampingHz','Damping Hz',500,20000,100],['width','Reverb width',0,1,.05]])r.append(control(label,m.reverb[key],(n,v)=>n.mixer.reverb[key]=v,{min,max,step}));r.append(control('Reverb return dB',m.reverbReturnDb,(n,v)=>n.mixer.reverbReturnDb=v,{min:-60,max:6,step:.5}),control('Mute reverb return',m.reverbMute,(n,v)=>n.mixer.reverbMute=v,{check:true}));reverb.append(r,meter('reverb','Reverb return'));root.append(reverb);
    }
    const notice=el('p','Meters show short-window channel sample peak/RMS and compressor gain reduction, not LUFS or true peak. Stems isolate each track through its own bus contribution; nonlinear bus compression means their sum may differ from the stereo mix.','fine');notice.id='mixNotice';root.append(notice);dialog('Mixer & effects · Core 3',root);
  }
  open.onclick=()=>run(show);
  const timer=setInterval(()=>{if(!document.getElementById('detailDialog')?.open||!document.getElementById('mixTarget'))return;const meters=studio.graph?.readMeters()||{};for(const [id,out] of meterRows){const v=meters[id];out.textContent=v?`Peak ${v.peakDb.toFixed(1)} dBFS · RMS ${v.rmsDb.toFixed(1)} dBFS · hold ${v.heldPeakDb.toFixed(1)} · GR ${v.reductionDb.toFixed(1)} dB${v.sidechainReductionDb<-.05?' · SC '+v.sidechainReductionDb.toFixed(1)+' dB':''}`:'Stopped · no active meter';out.classList.toggle('mixOver',!!v&&v.heldPeakDb>0);}},120);
  addEventListener('pagehide',()=>clearInterval(timer),{once:true});
  return {refresh(){open.disabled=!getState().owner||!!getState().busy||!!studio.protectedStart||!!studio.finalizingRecording||!!studio.recording;},open:show};
}
