import {enablePrecision,hasPrecision,noteName} from './precision-schema.js';
import {nearestNote} from './legacy.js';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function installPrecisionUI({getProject,getClip,getTrack,studio,edit,dialog,status,run,requireStopped}){
 let analysis=null;
 const E=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
 const btn=(text,fn,cls='')=>{const b=E('button',text,cls);b.onclick=()=>run(fn);return b;};
 function drawCanvas(canvas,frames,regions,duration){const dpr=devicePixelRatio||1,w=760,h=220;canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width='100%';canvas.style.height=h+'px';const x=canvas.getContext('2d');x.scale(dpr,dpr);x.fillStyle='#101014';x.fillRect(0,0,w,h);const notes=frames.filter(f=>Number.isFinite(f.note)).map(f=>f.note);if(!notes.length){x.fillStyle='#aaa';x.fillText('No confident pitched regions detected.',20,30);return;}const lo=Math.floor(Math.min(...notes)-2),hi=Math.ceil(Math.max(...notes)+2);for(let n=lo;n<=hi;n++){const y=h-(n-lo)/(hi-lo)*h;x.strokeStyle=n%12===0?'#ffffff28':'#ffffff10';x.beginPath();x.moveTo(0,y);x.lineTo(w,y);x.stroke();if(n%12===0){x.fillStyle='#888';x.fillText(noteName(n),4,y-3);}}x.strokeStyle='#b9a2ff';x.lineWidth=2;x.beginPath();let started=false;for(const f of frames){if(!Number.isFinite(f.note)||f.confidence<.72){started=false;continue;}const px=f.time/duration*w,py=h-(f.note-lo)/(hi-lo)*h;if(!started){x.moveTo(px,py);started=true;}else x.lineTo(px,py);}x.stroke();for(const r of regions){x.fillStyle='#a98cff22';x.fillRect(r.start/duration*w,0,(r.end-r.start)/duration*w,h);const py=h-(r.targetNote-lo)/(hi-lo)*h;x.strokeStyle='#ff8bb9aa';x.beginPath();x.moveTo(r.start/duration*w,py);x.lineTo(r.end/duration*w,py);x.stroke();}}
 async function analyze(){requireStopped();const p=getProject(),c=getClip(),t=getTrack();if(!c||t?.kind!=='vocal')throw Error('Select a vocal clip first.');analysis=await studio.analyzePrecision(c,t,p);status(analysis.regions.length+' pitched region(s) detected. Review targets before applying.');return analysis;}
 async function openPitch(){requireStopped();const p=getProject(),c=getClip(),t=getTrack();if(!c||t?.kind!=='vocal')throw Error('Select a vocal clip first.');if(!analysis||analysis.clipId!==c.id)await analyze();const root=E('div',undefined,'precision-editor'),canvas=E('canvas');const pending=analysis.regions.map(r=>({...r,targetNote:Math.round(r.targetNote),amount:1,transitionMs:35,enabled:true}));drawCanvas(canvas,analysis.frames,pending,c.duration);root.append(E('p','Pitch curve is analysis, not source audio. Pink targets are editable; applying creates reversible Core 4 metadata and leaves original PCM unchanged.','dialog-note'),canvas);
  const table=E('div',undefined,'precision-regions');for(const r of pending){const row=E('div',undefined,'precision-row');const label=E('strong',`${r.start.toFixed(2)}–${r.end.toFixed(2)} · ${noteName(Math.round(r.detectedNote))} · ${Math.round(r.confidence*100)}%`);const target=E('select');for(let n=Math.max(0,Math.round(r.detectedNote)-12);n<=Math.min(127,Math.round(r.detectedNote)+12);n++){const o=E('option',noteName(n));o.value=String(n);target.append(o);}target.value=String(r.targetNote);target.onchange=()=>{r.targetNote=Number(target.value);drawCanvas(canvas,analysis.frames,pending,c.duration);};const amount=E('input');amount.type='range';amount.min='0';amount.max='1';amount.step='.01';amount.value='1';amount.oninput=()=>r.amount=Number(amount.value);const enabled=E('input');enabled.type='checkbox';enabled.checked=true;enabled.onchange=()=>r.enabled=enabled.checked;row.append(label,E('span','Target'),target,E('span','Amount'),amount,E('span','Use'),enabled);table.append(row);}root.append(table,btn('Apply pitch regions',()=>{edit(next=>{const precision=enablePrecision(next,c.id);precision.pitchEnabled=true;precision.regions=pending.map((r,i)=>({id:'manual-'+i,start:r.start,end:r.end,targetNote:r.targetNote,amount:r.amount,transitionMs:r.transitionMs,enabled:r.enabled}));});status('Precision Tune applied non-destructively. Audition the selected clip and use Undo if needed.');},'primary'),btn('Clear manual pitch regions',()=>{edit(next=>{const precision=enablePrecision(next,c.id);precision.pitchEnabled=false;precision.regions=[];});status('Manual pitch regions cleared; source audio was not changed.');}));dialog('Precision Tune · note editor',root);}
 function openWarp(){requireStopped();const p=getProject(),c=getClip(),t=getTrack();if(!c||t?.kind!=='vocal')throw Error('Select a vocal clip first.');const root=E('div',undefined,'precision-editor');let markers=(c.precision?.warpMarkers||[]).map(m=>({...m}));const list=E('div',undefined,'precision-regions');const redraw=()=>{list.replaceChildren();markers.forEach((m,index)=>{const row=E('div',undefined,'precision-row');const source=E('span','Source '+m.source.toFixed(3)+'s'),dest=E('input');dest.type='number';dest.step='.005';dest.min='.001';dest.max=String(c.duration-.001);dest.value=String(m.dest);dest.onchange=()=>m.dest=Number(dest.value);row.append(source,E('span','Destination'),dest,btn('Remove',()=>{markers.splice(index,1);redraw();}));list.append(row);});};redraw();root.append(E('p','Warp anchors move timing inside this clip while preserving its overall start and end. The time-stretch path uses waveform-similarity overlap/add rather than playback-rate pitch shifting.','dialog-note'),list,btn('Add anchor at playhead',()=>{const relative=clamp(p.cursor-c.start,.001,c.duration-.001);if(markers.some(m=>Math.abs(m.source-relative)<.01))throw Error('Move the playhead away from an existing anchor.');markers.push({source:relative,dest:relative});markers.sort((a,b)=>a.source-b.source);redraw();}),btn('Apply warp anchors',()=>{const sorted=[...markers].sort((a,b)=>a.source-b.source);let d=0;for(const m of sorted){if(m.dest<=d)throw Error('Destination anchors must stay in increasing order.');d=m.dest;}edit(next=>{const precision=enablePrecision(next,c.id);precision.warpEnabled=true;precision.warpMarkers=sorted;});status('Precision Pocket warp saved. Audition the clip; Undo remains available.');},'primary'),btn('Clear warp',()=>{edit(next=>{const precision=enablePrecision(next,c.id);precision.warpEnabled=false;precision.warpMarkers=[];});status('Warp anchors cleared.');}));dialog('Precision Pocket · warp anchors',root);}
 return {openPitch,openWarp,analyze,active:()=>hasPrecision(getClip())};
}
