export const PRECISION_ENGINE='precision-1';
const num=(v,min,max,label)=>{if(typeof v!=='number'||!Number.isFinite(v)||v<min||v>max)throw Error(label+' must be between '+min+' and '+max+'.');};
const obj=(v,label)=>{if(!v||typeof v!=='object'||Array.isArray(v))throw Error('Invalid '+label+'.');};
export function newPrecision(){return {engine:PRECISION_ENGINE,enabled:true,pitchEnabled:false,warpEnabled:false,regions:[],warpMarkers:[]};}
export function hasPrecision(clip){return clip?.precision?.engine===PRECISION_ENGINE&&clip.precision.enabled===true;}
export function enablePrecision(project,clipId){const clip=project.clips.find(c=>c.id===clipId);if(!clip)throw Error('Select a clip first.');if(!clip.precision)clip.precision=newPrecision();clip.precision.enabled=true;project.version=Math.max(3,project.version||1);return clip.precision;}
export function validatePrecision(project){let used=false;for(const clip of project.clips||[]){if(clip.precision===undefined)continue;used=true;obj(clip.precision,'precision edit');const p=clip.precision;if(p.engine!==PRECISION_ENGINE||typeof p.enabled!=='boolean'||typeof p.pitchEnabled!=='boolean'||typeof p.warpEnabled!=='boolean')throw Error('Unsupported precision editor data.');if(!Array.isArray(p.regions)||p.regions.length>256||!Array.isArray(p.warpMarkers)||p.warpMarkers.length>64)throw Error('Precision edit contains too many regions or anchors.');if(p.pitchEnabled&&p.regions.length===0)throw Error('Precision pitch is enabled without note regions.');if(p.warpEnabled&&p.warpMarkers.length===0)throw Error('Precision warp is enabled without anchors.');
  let priorEnd=-1;for(const r of p.regions){obj(r,'pitch region');if(typeof r.id!=='string'||r.id.length>100)throw Error('Invalid pitch region id.');num(r.start,0,clip.duration,'Pitch region start');num(r.end,r.start+0.005,clip.duration,'Pitch region end');if(r.start<priorEnd-1e-6)throw Error('Pitch regions may not overlap.');priorEnd=r.end;if(!Number.isInteger(r.targetNote)||r.targetNote<0||r.targetNote>127)throw Error('Target note must be a MIDI note.');num(r.amount,0,1,'Pitch amount');num(r.transitionMs,0,250,'Pitch transition');if(typeof r.enabled!=='boolean')throw Error('Invalid pitch region state.');}
  let lastSource=0,lastDest=0;for(const m of p.warpMarkers){obj(m,'warp marker');num(m.source,0.001,clip.duration-0.001,'Warp source');num(m.dest,0.001,clip.duration-0.001,'Warp destination');if(m.source<=lastSource||m.dest<=lastDest)throw Error('Warp markers must stay ordered in source and destination time.');lastSource=m.source;lastDest=m.dest;}
 }
 if(used&&![3,4].includes(project.version))throw Error('Precision edits require a Core 4/5 compatible project.');if(project.version===3&&!used)throw Error('Core 4 version 3 project is missing precision edit data.');
}
export function precisionFingerprint(clip){return clip?.precision?JSON.stringify(clip.precision):'';}
export function noteName(midi){const names=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];return names[((midi%12)+12)%12]+(Math.floor(midi/12)-1);}
