import {clamp} from './model.js';
import {yin} from './core.js';
import {nearestNote} from './legacy.js';
const midiToHz=n=>440*Math.pow(2,(n-69)/12);
const hzToMidi=hz=>69+12*Math.log2(hz/440);
const median=a=>{if(!a.length)return 0;const b=[...a].sort((x,y)=>x-y);return b[Math.floor(b.length/2)];};
export function analyzePitch(input,rate,{root=0,scale='chromatic',sections=[],start=0}={}){
  if(!(input instanceof Float32Array)||!Number.isFinite(rate)||rate<8000)throw Error('Invalid pitch-analysis audio.');
  const size=1024,hop=256,frames=[];
  for(let at=0;at+size<=input.length;at+=hop){const frame=input.subarray(at,at+size),p=yin(frame,rate,55,1000);const time=at/rate;const note=p.hz?hzToMidi(p.hz):null;const section=sections.find(s=>start+time>=s.start&&start+time<s.end);const key=section||{root,scale};frames.push({time,note,confidence:p.confidence,target:note===null?null:nearestNote(note,key.root,key.scale)});}
  const regions=[];let current=[];const finish=()=>{if(current.length<2){current=[];return;}const notes=current.map(f=>f.note).filter(Number.isFinite),targets=current.map(f=>f.target).filter(Number.isFinite);const detected=median(notes),target=Math.round(median(targets));regions.push({id:'pr-'+regions.length,start:current[0].time,end:Math.min(input.length/rate,current[current.length-1].time+size/rate),detectedNote:detected,targetNote:target,confidence:current.reduce((s,f)=>s+f.confidence,0)/current.length,amount:1,transitionMs:35,enabled:true});current=[];};
  for(const f of frames){if(f.note===null||f.confidence<0.78){finish();continue;}if(current.length){const prior=current[current.length-1];if(f.time-prior.time>hop/rate*1.6||Math.abs(f.note-median(current.map(x=>x.note)))>1.5)finish();}current.push(f);}finish();
  return {frames,regions};
}
function peakNear(input,expected,radius){let best=Math.round(expected),value=-1;const lo=Math.max(1,Math.floor(expected-radius)),hi=Math.min(input.length-2,Math.ceil(expected+radius));for(let i=lo;i<=hi;i++){const v=Math.abs(input[i]);if(v>value){value=v;best=i;}}return best;}
function psolaSegment(input,rate,start,end,detectedNote,targetNote){const length=end-start;if(length<32)return input.slice(start,end);const ratio=Math.pow(2,(targetNote-detectedNote)/12);if(Math.abs(ratio-1)<0.002)return input.slice(start,end);const period=clamp(rate/midiToHz(detectedNote),rate/1000,rate/55),radius=Math.max(12,Math.min(Math.floor(period*1.25),Math.floor(length/4)));if(radius<6)return input.slice(start,end);
  const inMarks=[];let pos=start+radius;while(pos<end-radius){const mark=peakNear(input,pos,period*0.22);if(!inMarks.length||mark-inMarks[inMarks.length-1]>period*0.45)inMarks.push(mark);pos=mark+period;}if(inMarks.length<3)return input.slice(start,end);
  const out=new Float64Array(length),weights=new Float64Array(length),outPeriod=period/ratio;for(let outMark=radius;outMark<length-radius;outMark+=outPeriod){const progress=outMark/length,targetInput=start+progress*length;let chosen=inMarks[0],distance=Math.abs(chosen-targetInput);for(const mark of inMarks){const d=Math.abs(mark-targetInput);if(d<distance){chosen=mark;distance=d;}else if(mark>targetInput&&d>distance)break;}for(let k=-radius;k<=radius;k++){const oi=Math.round(outMark)+k,ii=chosen+k;if(oi<0||oi>=length||ii<start||ii>=end)continue;const w=0.5+0.5*Math.cos(Math.PI*k/radius);out[oi]+=input[ii]*w;weights[oi]+=w;}}
  const result=new Float32Array(length);for(let i=0;i<length;i++)result[i]=weights[i]>1e-8?out[i]/weights[i]:input[start+i];return result;}
export function precisionPitch(input,rate,settings,precision,{root=0,scale='chromatic',sections=[],start=0}={}){const analysis=analyzePitch(input,rate,{root,scale,sections,start});const output=input.slice();const edits=precision?.regions||[];for(const region of analysis.regions){const midpoint=(region.start+region.end)/2;const manual=edits.find(e=>e.enabled&&midpoint>=e.start&&midpoint<e.end);const amount=manual?.amount??settings.tune??0;const targetBase=manual?.targetNote??region.targetNote;const target=region.detectedNote+(targetBase-region.detectedNote)*amount+(settings.shift||0);if(Math.abs(target-region.detectedNote)<0.01)continue;const a=Math.max(0,Math.floor(region.start*rate)),b=Math.min(input.length,Math.ceil(region.end*rate));const shifted=psolaSegment(input,rate,a,b,region.detectedNote,target);const fade=Math.min(Math.floor((manual?.transitionMs??35)/1000*rate),Math.floor((b-a)/3));for(let i=0;i<shifted.length;i++){let mix=1;if(fade){if(i<fade)mix=i/fade;else if(i>shifted.length-fade)mix=(shifted.length-i)/fade;}output[a+i]=output[a+i]*(1-clamp(mix,0,1))+shifted[i]*clamp(mix,0,1);}}
  if(settings.sub>0){for(const region of analysis.regions){const a=Math.max(0,Math.floor(region.start*rate)),b=Math.min(input.length,Math.ceil(region.end*rate));const lower=psolaSegment(input,rate,a,b,region.detectedNote,region.detectedNote-12);for(let i=0;i<lower.length;i++)output[a+i]=output[a+i]*(1-settings.sub*0.45)+lower[i]*settings.sub*0.45;}}
  return output;}
function similarity(out,input,outStart,inStart,overlap){let ab=0,aa=0,bb=0;for(let i=0;i<overlap;i++){const a=out[outStart+i]||0,b=input[inStart+i]||0;ab+=a*b;aa+=a*a;bb+=b*b;}return ab/Math.sqrt(Math.max(1e-12,aa*bb));}
function stretchSegment(input,outLength){const inLength=input.length;if(outLength===inLength)return input.slice();if(inLength<512||outLength<512){const out=new Float32Array(outLength);for(let i=0;i<outLength;i++){const p=i*(inLength-1)/Math.max(1,outLength-1),k=Math.floor(p),t=p-k;out[i]=input[k]*(1-t)+input[Math.min(k+1,inLength-1)]*t;}return out;}
  const frame=Math.min(1024,Math.floor(inLength/4)*2),overlap=Math.floor(frame/4),hopOut=frame-overlap,ratio=outLength/inLength,hopIn=hopOut/ratio,search=Math.min(128,Math.floor(overlap/2));const out=new Float32Array(outLength),weight=new Float32Array(outLength);let expected=0,outAt=0,first=true;
  while(outAt<outLength){let inAt=Math.round(expected);if(!first&&outAt>=overlap){let best=inAt,bestScore=-Infinity;for(let candidate=Math.max(0,inAt-search);candidate<=Math.min(inLength-frame,inAt+search);candidate+=4){const score=similarity(out,input,outAt,candidate,Math.min(overlap,outLength-outAt));if(score>bestScore){bestScore=score;best=candidate;}}inAt=best;}inAt=clamp(inAt,0,Math.max(0,inLength-frame));for(let i=0;i<frame&&outAt+i<outLength&&inAt+i<inLength;i++){const edge=Math.min(1,i/Math.max(1,overlap),(frame-1-i)/Math.max(1,overlap));const w=first?1:clamp(edge,0,1);out[outAt+i]+=input[inAt+i]*w;weight[outAt+i]+=w;}first=false;outAt+=hopOut;expected+=hopIn;}
  for(let i=0;i<outLength;i++)if(weight[i]>1e-6)out[i]/=weight[i];return out;}
export function warpAudio(input,rate,markers=[]){if(!markers?.length)return input.slice();const duration=input.length/rate,points=[{source:0,dest:0},...markers,{source:duration,dest:duration}],output=new Float32Array(input.length);for(let i=0;i<points.length-1;i++){const a=points[i],b=points[i+1],s0=Math.round(a.source*rate),s1=Math.round(b.source*rate),d0=Math.round(a.dest*rate),d1=Math.round(b.dest*rate);if(s1<=s0||d1<=d0)throw Error('Warp anchors crossed.');const stretched=stretchSegment(input.subarray(s0,s1),d1-d0);output.set(stretched.subarray(0,Math.min(stretched.length,output.length-d0)),d0);}return output;}
export function applyPrecision(input,rate,settings,precision,context={}){let audio=precision?.warpEnabled&&precision?.warpMarkers?.length?warpAudio(input,rate,precision.warpMarkers):input.slice();if(precision?.pitchEnabled)audio=precisionPitch(audio,rate,settings,precision,context);return audio;}
