import {hasMixer,enableMixer,strip} from './mixer-schema.js';
export const PRODUCER_ENGINE='producer-1';
const finite=(v,min,max,label)=>{if(typeof v!=='number'||!Number.isFinite(v)||v<min||v>max)throw Error(label+' must be between '+min+' and '+max+'.');};
const obj=(v,label)=>{if(!v||typeof v!=='object'||Array.isArray(v))throw Error('Invalid '+label+'.');};
const flag=(v,label)=>{if(typeof v!=='boolean')throw Error('Invalid '+label+'.');};
export const hasProducer=p=>p?.producer?.engine===PRODUCER_ENGINE&&p.producer.enabled===true;
export function newProducer(project){const buses=project?.mixer?.buses||[];return {engine:PRODUCER_ENGINE,enabled:true,
  automation:{enabled:true,lanes:[]},
  sidechain:{enabled:false,keyBus:buses[0]?.id||'',targetBus:buses[3]?.id||buses[1]?.id||'',threshold:-24,ratio:4,knee:6,attackMs:5,releaseMs:180,maxReductionDb:12},
  grim:{enabled:false,targetBus:buses[0]?.id||'',darkness:.35,weight:.3,bite:.25,clarity:.55,space:.22,glitch:0},
  mastering:{enabled:false,targetLufs:-14,ceilingDbtp:-1,limiterReleaseMs:120,width:1,drive:0,style:'Balanced'}};}
export function enableProducer(project){if(!hasMixer(project))enableMixer(project);if(!project.producer)project.producer=newProducer(project);project.producer.enabled=true;project.version=4;return project;}
export function targetRange(project,target){if(target==='master:gainDb')return [-24,6];const [kind,id,param]=String(target||'').split(':');if(kind==='track'&&project.tracks.some(t=>t.id===id)){
  if(param==='gainDb')return [-60,12];if(param==='pan')return [-1,1];if(param==='delaySend'||param==='reverbSend')return [0,1];
 }if(kind==='bus'&&project.mixer?.buses.some(b=>b.id===id)&&param==='gainDb')return [-60,12];return null;}
export function automationTargetOptions(project){const rows=[];for(const t of project.tracks){rows.push([`track:${t.id}:gainDb`,`Track · ${t.name} · level`],[`track:${t.id}:pan`,`Track · ${t.name} · pan`]);if(project.mixer){rows.push([`track:${t.id}:delaySend`,`Track · ${t.name} · delay send`],[`track:${t.id}:reverbSend`,`Track · ${t.name} · reverb send`]);}}
 for(const b of project.mixer?.buses||[])rows.push([`bus:${b.id}:gainDb`,`Bus · ${b.name} · level`]);if(project.mixer)rows.push(['master:gainDb','Main · trim']);return rows;}
export function laneFor(project,target){return project.producer?.automation?.lanes?.find(l=>l.target===target)||null;}
export function automationValue(project,target,time,fallback){const lane=laneFor(project,target);if(!project.producer?.automation?.enabled||!lane?.enabled||!lane.points.length)return fallback;const points=lane.points;if(time<=points[0].time)return points[0].value;if(time>=points[points.length-1].time)return points[points.length-1].value;let i=1;while(i<points.length&&points[i].time<time)i++;const a=points[i-1],b=points[i],span=b.time-a.time;if(span<=1e-9)return b.value;const t=(time-a.time)/span;if(b.curve==='hold')return a.value;return a.value+(b.value-a.value)*t;}
export function ensureLane(project,target){const range=targetRange(project,target);if(!range)throw Error('Unsupported automation target.');let lane=laneFor(project,target);if(!lane){lane={id:'auto-'+crypto.randomUUID(),target,enabled:true,points:[]};project.producer.automation.lanes.push(lane);}return lane;}
export function producerChangeIsLive(a,b){if(!hasProducer(a)||!hasProducer(b))return false;const skeleton=p=>{const x=structuredClone(p.producer);delete x.mastering;const lanes=x.automation?.lanes||[];x.automation={enabled:x.automation.enabled,lanes:lanes.map(l=>({id:l.id,target:l.target,enabled:l.enabled,points:l.points}))};x.sidechain={...x.sidechain,enabled:undefined,threshold:undefined,ratio:undefined,knee:undefined,attackMs:undefined,releaseMs:undefined,maxReductionDb:undefined};x.grim={...x.grim,darkness:undefined,weight:undefined,bite:undefined,clarity:undefined,space:undefined,glitch:undefined,enabled:undefined};return JSON.stringify(x);};return skeleton(a)===skeleton(b);}
export function validateProducer(project){const p=project.producer;if(p===undefined){if(project.version===4)throw Error('Core 5 project is missing producer data.');return;}obj(p,'producer tools');if(p.engine!==PRODUCER_ENGINE||project.version!==4)throw Error('Producer tools require Core 5 project format v4.');flag(p.enabled,'producer enabled');if(!hasMixer(project))throw Error('Core 5 producer tools require the Core 3 mixer.');
 obj(p.automation,'automation');flag(p.automation.enabled,'automation enabled');if(!Array.isArray(p.automation.lanes)||p.automation.lanes.length>96)throw Error('Too many automation lanes.');const laneIds=new Set(),targets=new Set();for(const lane of p.automation.lanes){obj(lane,'automation lane');if(typeof lane.id!=='string'||lane.id.length>120||laneIds.has(lane.id)||typeof lane.target!=='string'||targets.has(lane.target))throw Error('Invalid or duplicate automation lane.');laneIds.add(lane.id);targets.add(lane.target);flag(lane.enabled,'automation lane');const range=targetRange(project,lane.target);if(!range)throw Error('Automation lane points at a missing control.');if(!Array.isArray(lane.points)||lane.points.length>512)throw Error('Automation lane has too many points.');let last=-1;for(const point of lane.points){obj(point,'automation point');finite(point.time,0,21600,'Automation time');finite(point.value,range[0],range[1],'Automation value');if(point.time<=last)throw Error('Automation points must stay in increasing time order.');last=point.time;if(!['linear','hold'].includes(point.curve))throw Error('Unsupported automation curve.');}}
 obj(p.sidechain,'sidechain');flag(p.sidechain.enabled,'sidechain enabled');if(p.sidechain.enabled){if(!project.mixer.buses.some(b=>b.id===p.sidechain.keyBus)||!project.mixer.buses.some(b=>b.id===p.sidechain.targetBus)||p.sidechain.keyBus===p.sidechain.targetBus)throw Error('Choose different existing key and target buses for sidechain ducking.');}for(const [k,min,max] of [['threshold',-60,0],['ratio',1,20],['knee',0,24],['attackMs',.1,100],['releaseMs',10,2000],['maxReductionDb',0,30]])finite(p.sidechain[k],min,max,'Sidechain '+k);
 obj(p.grim,'GRIM rack');flag(p.grim.enabled,'GRIM rack enabled');if(p.grim.targetBus&&!project.mixer.buses.some(b=>b.id===p.grim.targetBus))throw Error('GRIM rack points at a missing bus.');for(const k of ['darkness','weight','bite','clarity','space','glitch'])finite(p.grim[k],0,1,'GRIM '+k);
 obj(p.mastering,'producer mastering');flag(p.mastering.enabled,'producer mastering');finite(p.mastering.targetLufs,-24,-8,'Target LUFS');finite(p.mastering.ceilingDbtp,-6,-.1,'True-peak ceiling');finite(p.mastering.limiterReleaseMs,20,1000,'Limiter release');finite(p.mastering.width,0,1.5,'Master width');finite(p.mastering.drive,0,.35,'Master drive');if(!['Dynamic','Balanced','Aggressive'].includes(p.mastering.style))throw Error('Unknown mastering intent.');
}
export function producerPreset(name,project){const p=newProducer(project);p.enabled=true;if(name==='Vocal focus'){p.sidechain.enabled=!!(p.sidechain.keyBus&&p.sidechain.targetBus);p.sidechain.threshold=-28;p.sidechain.ratio=5;p.sidechain.maxReductionDb=9;p.grim.enabled=false;p.mastering={...p.mastering,enabled:true,targetLufs:-14,ceilingDbtp:-1,style:'Balanced'};}
 else if(name==='GRIM main'){p.grim={...p.grim,enabled:true,darkness:.45,weight:.45,bite:.38,clarity:.62,space:.25,glitch:.05};p.mastering={...p.mastering,enabled:true,targetLufs:-13,ceilingDbtp:-1,drive:.025,style:'Balanced'};}
 else if(name==='GRIM abyss'){p.grim={...p.grim,enabled:true,darkness:.78,weight:.72,bite:.55,clarity:.42,space:.38,glitch:.14};p.mastering={...p.mastering,enabled:true,targetLufs:-12,ceilingDbtp:-1,drive:.05,style:'Aggressive'};}
 else if(name==='Dynamic mix'){p.mastering={...p.mastering,enabled:true,targetLufs:-16,ceilingDbtp:-1.5,style:'Dynamic'};}
 else throw Error('Unknown producer preset.');return p;}
