const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const db=v=>20*Math.log10(Math.max(1e-12,v));
const gain=d=>10**(d/20);
export class SidechainKernel{
  constructor(rate){this.rate=rate;this.env=0;this.gain=1;this.reductionDb=0;}
  next(key,p){const peak=Math.max(0,Number.isFinite(key)?key:0),attack=Math.exp(-1/(Math.max(.1,p.attackMs)*.001*this.rate)),release=Math.exp(-1/(Math.max(10,p.releaseMs)*.001*this.rate));const c=peak>this.env?attack:release;this.env=c*this.env+(1-c)*peak;const level=db(this.env),over=level-p.threshold;let reduction=0;if(p.enabled&&over>0){const soft=p.knee?clamp((over+p.knee/2)/p.knee,0,1):1;const full=over*(1-1/p.ratio);reduction=-Math.min(p.maxReductionDb,full*soft);}const target=gain(reduction);const gc=target<this.gain?attack:release;this.gain=gc*this.gain+(1-gc)*target;this.reductionDb=db(this.gain);return this.gain;}}
export class GrimKernel{
  constructor(rate){this.rate=rate;this.low=[0,0];this.clarityLow=[0,0];this.darkLow=[0,0];this.frame=0;}
  processSample(x,ch,p){if(!Number.isFinite(x))x=0;const lowA=1-Math.exp(-2*Math.PI*180/this.rate),presenceA=1-Math.exp(-2*Math.PI*2800/this.rate);this.low[ch]+=lowA*(x-this.low[ch]);this.clarityLow[ch]+=presenceA*(x-this.clarityLow[ch]);const high=x-this.clarityLow[ch];let y=x+this.low[ch]*p.weight*.9+high*p.clarity*.55;const darkCut=18000-(14500*p.darkness);const darkA=1-Math.exp(-2*Math.PI*darkCut/this.rate);this.darkLow[ch]+=darkA*(y-this.darkLow[ch]);y=y*(1-p.darkness*.65)+this.darkLow[ch]*(p.darkness*.65);if(p.bite>0){const drive=1+p.bite*9;y=y*(1-p.bite*.55)+Math.tanh(y*drive)/Math.tanh(drive)*p.bite*.55;}if(p.glitch>0){const beat=this.frame/this.rate*(p.bpm||120)/60,slice=Math.floor(beat*4),phase=beat*4-slice;const pattern=(slice%8===3||slice%8===6)?1:0;const gate=pattern&&phase>.52?1-p.glitch*.92:1;y*=gate;}return Number.isFinite(y)?y:0;}
  processFrame(left,right,p){const l=this.processSample(left,0,p),r=this.processSample(right,1,p);this.frame++;return [l,r];}}
function biquadCoefficients(type,rate,freq,q=0.7071,gainDb=0){const A=10**(gainDb/40),w=2*Math.PI*freq/rate,c=Math.cos(w),s=Math.sin(w),alpha=s/(2*q);let b0,b1,b2,a0,a1,a2;if(type==='highpass'){b0=(1+c)/2;b1=-(1+c);b2=b0;a0=1+alpha;a1=-2*c;a2=1-alpha;}else if(type==='highshelf'){const sqrtA=Math.sqrt(A),two=2*sqrtA*alpha;b0=A*((A+1)+(A-1)*c+two);b1=-2*A*((A-1)+(A+1)*c);b2=A*((A+1)+(A-1)*c-two);a0=(A+1)-(A-1)*c+two;a1=2*((A-1)-(A+1)*c);a2=(A+1)-(A-1)*c-two;}else throw Error('Unsupported filter.');return [b0/a0,b1/a0,b2/a0,a1/a0,a2/a0];}
function filterChannel(input,coeff){const [b0,b1,b2,a1,a2]=coeff,out=new Float64Array(input.length);let x1=0,x2=0,y1=0,y2=0;for(let i=0;i<input.length;i++){const x=input[i],y=b0*x+b1*x1+b2*x2-a1*y1-a2*y2;out[i]=y;x2=x1;x1=x;y2=y1;y1=y;}return out;}
export function kWeight(channels,rate){const shelf=biquadCoefficients('highshelf',rate,1681.974450955533,0.7071752369554196,3.99984385397),hp=biquadCoefficients('highpass',rate,38.13547087602444,0.5003270373238773,0);return channels.map(c=>filterChannel(filterChannel(c,shelf),hp));}
function loudnessFromEnergy(e){return -0.691+10*Math.log10(Math.max(1e-20,e));}
export function integratedLufs(channels,rate){if(!Array.isArray(channels)||!channels.length||channels.some(c=>!(c instanceof Float32Array)&&!(c instanceof Float64Array)))throw Error('Invalid loudness audio.');const weighted=kWeight(channels,rate),block=Math.max(1,Math.round(rate*.4)),hop=Math.max(1,Math.round(rate*.1)),energies=[];for(let at=0;at+block<=weighted[0].length;at+=hop){let e=0;for(const c of weighted){let s=0;for(let i=at;i<at+block;i++)s+=c[i]*c[i];e+=s/block;}energies.push(e);}if(!energies.length){let e=0;for(const c of weighted){let s=0;for(const v of c)s+=v*v;e+=s/Math.max(1,c.length);}return loudnessFromEnergy(e);}const absolute=energies.filter(e=>loudnessFromEnergy(e)>-70);if(!absolute.length)return -Infinity;const ungated=absolute.reduce((a,b)=>a+b,0)/absolute.length,relative=loudnessFromEnergy(ungated)-10,gated=absolute.filter(e=>loudnessFromEnergy(e)>relative);return loudnessFromEnergy((gated.length?gated:absolute).reduce((a,b)=>a+b,0)/(gated.length||absolute.length));}
function percentile(values,p){if(!values.length)return 0;const sorted=[...values].sort((a,b)=>a-b),x=(sorted.length-1)*p,i=Math.floor(x),f=x-i;return sorted[i]+(sorted[Math.min(i+1,sorted.length-1)]-sorted[i])*f;}
export function loudnessRange(channels,rate){const weighted=kWeight(channels,rate),block=Math.max(1,Math.round(rate*3)),hop=Math.max(1,Math.round(rate)),values=[];for(let at=0;at+block<=weighted[0].length;at+=hop){let e=0;for(const c of weighted){let s=0;for(let i=at;i<at+block;i++)s+=c[i]*c[i];e+=s/block;}const l=loudnessFromEnergy(e);if(l>-70)values.push(l);}if(values.length<2)return 0;const integrated=integratedLufs(channels,rate),gated=values.filter(v=>v>integrated-20);return Math.max(0,percentile(gated,.95)-percentile(gated,.1));}
const sinc=x=>Math.abs(x)<1e-12?1:Math.sin(Math.PI*x)/(Math.PI*x);
const firPhases=(()=>{const taps=12,result=[];for(const phase of [.25,.5,.75]){const weights=[];let sum=0;for(let k=-taps;k<=taps;k++){const x=k-phase,w=sinc(x)*(.5+.5*Math.cos(Math.PI*x/(taps+1)));weights.push(w);sum+=w;}result.push(weights.map(v=>v/sum));}return {taps,result};})();
export function truePeak(channels){let peak=0;const {taps,result}=firPhases;for(const c of channels){for(const v of c)peak=Math.max(peak,Math.abs(v));for(let i=0;i<c.length-1;i++){for(const weights of result){let y=0,idx=0;for(let k=-taps;k<=taps;k++,idx++){const sample=c[clamp(i+k,0,c.length-1)]||0;y+=sample*weights[idx];}peak=Math.max(peak,Math.abs(y));}}}return {peak,dbtp:db(peak)};}
export function masteringMetrics(channels,rate){const tp=truePeak(channels),lufs=integratedLufs(channels,rate),lra=loudnessRange(channels,rate);let samplePeak=0,rms=0,n=0;for(const c of channels)for(const v of c){samplePeak=Math.max(samplePeak,Math.abs(v));rms+=v*v;n++;}return {integratedLufs:lufs,loudnessRange:lra,truePeak:tp.peak,truePeakDbtp:tp.dbtp,samplePeakDb:db(samplePeak),rmsDb:10*Math.log10(Math.max(1e-20,rms/Math.max(1,n)))};}
function widthProcess(channels,width){if(channels.length<2||width===1)return channels.map(c=>Float32Array.from(c));const n=channels[0].length,l=new Float32Array(n),r=new Float32Array(n);for(let i=0;i<n;i++){const mid=(channels[0][i]+channels[1][i])*.5,side=(channels[0][i]-channels[1][i])*.5*width;l[i]=mid+side;r[i]=mid-side;}return [l,r];}
function driveProcess(channels,amount){if(!amount)return channels.map(c=>Float32Array.from(c));const k=1+amount*8,norm=Math.tanh(k);return channels.map(c=>Float32Array.from(c,v=>v*(1-amount)+Math.tanh(v*k)/norm*amount));}
function lookaheadLimit(channels,rate,ceilingDbtp,releaseMs){const limit=gain(ceilingDbtp),n=channels[0].length,look=Math.max(1,Math.round(rate*.005)),peaks=new Float32Array(n);for(let i=0;i<n;i++){let p=0;for(const c of channels)p=Math.max(p,Math.abs(c[i]));peaks[i]=p;}const deque=[],future=new Float32Array(n);let tail=0;for(let i=0;i<n;i++){const end=Math.min(n-1,i+look);while(tail<=end){while(deque.length&&peaks[deque[deque.length-1]]<=peaks[tail])deque.pop();deque.push(tail++);}while(deque.length&&deque[0]<i)deque.shift();future[i]=peaks[deque[0]]||0;}const out=channels.map(()=>new Float32Array(n)),release=Math.exp(-1/(Math.max(20,releaseMs)*.001*rate));let g=1,maxReduction=0;for(let i=0;i<n;i++){const target=future[i]>limit?limit/future[i]:1;if(target<g)g=target;else g=release*g+(1-release)*target;maxReduction=Math.min(maxReduction,db(g));for(let ch=0;ch<channels.length;ch++)out[ch][i]=channels[ch][i]*g;}return {channels:out,maxReductionDb:maxReduction};}
export function masterProducer(channels,rate,settings){if(!settings?.enabled)return {channels:channels.map(c=>Float32Array.from(c)),before:masteringMetrics(channels,rate),after:masteringMetrics(channels,rate),gainDb:0,maxReductionDb:0};const before=masteringMetrics(channels,rate);let out=widthProcess(channels,settings.width);out=driveProcess(out,settings.drive);const measured=integratedLufs(out,rate),gainDb=Number.isFinite(measured)?clamp(settings.targetLufs-measured,-12,12):0,g=gain(gainDb);out=out.map(c=>Float32Array.from(c,v=>v*g));let limited=lookaheadLimit(out,rate,settings.ceilingDbtp,settings.limiterReleaseMs);out=limited.channels;let after=masteringMetrics(out,rate);if(after.truePeakDbtp>settings.ceilingDbtp+.02){const trim=gain(settings.ceilingDbtp-after.truePeakDbtp-.02);out=out.map(c=>Float32Array.from(c,v=>v*trim));after=masteringMetrics(out,rate);}return {channels:out,before,after,gainDb,maxReductionDb:limited.maxReductionDb};}
